### ISSUE TITLE
update path/libpath/manpath/etc with current path

### ISSUE THREAD

**Issue by lbdyck** [wizardofzos/gitmaster#6]
Instead of inserting the install directory in the envfile use $PWD and suffix $PATH/$MANPATH/$LIBPATH etc. rather than using the current values as those can change

this makes it easy to copy the installation

**Comment by wizardofzos** [comment]
Dunno quite what you mean?

The envfile takes the 'install destination' and creates the PATH etc ones?

I've just installed to /prj/git002 and get this:

```
declare -x MANPATH="/prj/git002/less/share/man:/prj/git002/ncurses/share/man:/prj/git002/bash/share/man:/usr/man/%L:/zdo/conda/envs/ispfgit/man"
declare -x NCURSES_HOME="/prj/git002/ncurses"
```

**Comment by lbdyck** [comment]
It does but those are hardcoded in the envfile instead of generalized. Lionel B. Dyck <sdg ><Website: www.lbdsoftware.comSent from my iPhone 12 ProWorry more about your character than your reputation.  Character is what you are, reputation merely what others think you are." - John Wooden On Feb 23, 2023, at 3:51 PM, wizardofzos ***@***.***> wrote:﻿
Dunno quite what you mean?
The envfile takes the 'install destination' and creates the PATH etc ones?
I've just installed to /prj/git002 and get this:
declare -x MANPATH="/prj/git002/less/share/man:/prj/git002/ncurses/share/man:/prj/git002/bash/share/man:/usr/man/%L:/zdo/conda/envs/ispfgit/man"
declare -x NCURSES_HOME="/prj/git002/ncurses"

**Comment by lbdyck** [comment]
my point is that if you use this then it is fully generalized and the installation directory can be copied/moved and the active environment can be changed without having to rebuild the envfile.

[envfile.txt](https://github.com/wizardofzos/gitmaster/files/10823903/envfile.txt)

**Comment by wizardofzos** [comment]
True,

But i don't feel the installer-one-click should take post processing into account...If one wants it at another location, just run the installer again pointing to the new location...  Or run a 'master-sed'  to change the envfile :)

The whole  idea was/is you install it to where you want it...and gitmaster takes care of it.. :)

Closing for now

**Comment by lbdyck** [comment]
Please reconsider - the sample envfile i provided makes the gitmaaster install simple and easy for use with gitmaster install and then to copy/move the installation to somewhere else.
